import { useState } from "react";
import { useCombinedFinancialData } from "@/hooks/useCombinedFinancialData";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { 
  DollarSign, 
  TrendingUp, 
  Download, 
  Loader2,
  BarChart3,
  Target,
  Share2,
  CheckCircle2,
  FileText,
  Settings,
  Sparkles,
  Eye
} from "lucide-react";
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer,
  Area,
  AreaChart
} from "recharts";
import { CFOAIChat } from "@/components/cfo/CFOAIChat";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import jsPDF from "jspdf";

export default function CombinedFinancialModels() {
  const { toast } = useToast();
  const [showShareModal, setShowShareModal] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [aiScenario, setAiScenario] = useState<"conservative" | "base" | "aggressive">("base");
  const [activeTab, setActiveTab] = useState("proforma");
  
  const getScenarioId = () => {
    return undefined;
  };

  const {
    monthlyProjections,
    yearlySummaries,
    isLoading,
  } = useCombinedFinancialData(getScenarioId());

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const formatPercentage = (value: number) => {
    return `${value.toFixed(1)}%`;
  };

  const getScenarioMultiplier = (scenario: "conservative" | "base" | "aggressive") => {
    switch (scenario) {
      case "conservative": return 0.75;
      case "aggressive": return 1.35;
      default: return 1.0;
    }
  };

  const getAIScenarioData = () => {
    const multiplier = getScenarioMultiplier(aiScenario);
    return yearlySummaries.map(year => ({
      ...year,
      totalRevenue: year.totalRevenue * multiplier,
      netProfit: year.netProfit * multiplier,
      subscriptionRevenue: year.subscriptionRevenue * multiplier,
      adRevenue: year.adRevenue * multiplier,
    }));
  };

  const handleExportPDF = (type: "ai" | "custom") => {
    const doc = new jsPDF();
    const data = type === "ai" ? getAIScenarioData() : yearlySummaries;
    const title = type === "ai" ? `AI-Generated Pro Forma (${aiScenario})` : "Custom 3-Year Pro Forma";
    
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, 210, 40, "F");
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("Combined 3-Year Revenue Model", 20, 20);
    doc.setFontSize(12);
    doc.text(title, 20, 30);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("3-Year Summary", 20, 55);
    
    let yPos = 70;
    data.forEach((year) => {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`Year ${year.year}`, 20, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(`Total Revenue: ${formatCurrency(year.totalRevenue)}`, 30, yPos + 7);
      doc.text(`  Subscriptions: ${formatCurrency(year.subscriptionRevenue)}`, 40, yPos + 14);
      doc.text(`  Ads: ${formatCurrency(year.adRevenue)}`, 40, yPos + 21);
      doc.text(`Net Profit: ${formatCurrency(year.netProfit)}`, 30, yPos + 28);
      yPos += 50;
    });
    
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Seeksy Financial Models | ${new Date().toLocaleDateString()}`,
      20,
      285
    );
    
    doc.save(`seeksy-combined-proforma-${type}.pdf`);
    toast({ title: "PDF exported successfully" });
  };

  const handleExportExcel = (type: "ai" | "custom") => {
    const data = type === "ai" ? getAIScenarioData() : yearlySummaries;
    const headers = ["Year", "Subscription Revenue", "Ad Revenue", "Total Revenue", "Total Payouts", "Net Profit", "Gross Margin %"];
    const rows = data.map(year => [
      year.year,
      year.subscriptionRevenue.toFixed(2),
      year.adRevenue.toFixed(2),
      year.totalRevenue.toFixed(2),
      year.totalPayouts.toFixed(2),
      year.netProfit.toFixed(2),
      year.grossMargin.toFixed(2),
    ]);
    
    const csvContent = [headers, ...rows].map(row => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `combined-proforma-${type}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Excel file exported successfully" });
  };

  const handleShareWithBoard = async () => {
    setIsSharing(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const reportData = {
        scenario: aiScenario,
        yearlySummaries: yearlySummaries,
        generatedAt: new Date().toISOString()
      };

      const { error } = await supabase
        .from('board_shared_reports' as any)
        .insert({
          report_type: 'custom_proforma',
          report_name: 'Custom 3-Year Combined Pro Forma',
          report_data: reportData,
          shared_by: user.id,
          is_active: true
        } as any);

      if (error) throw error;

      toast({ 
        title: "Pro Forma shared with Board Portal",
        description: "Board members can now access this report."
      });
      setShowShareModal(false);
    } catch (err) {
      console.error('Share error:', err);
      toast({ 
        title: "Error sharing report", 
        variant: "destructive" 
      });
    } finally {
      setIsSharing(false);
    }
  };

  if (isLoading) {
    return (
      <div className="mx-auto max-w-7xl px-6 py-6 flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const aiData = getAIScenarioData();
  const year3AI = aiData[2] || { totalRevenue: 0, netProfit: 0 };
  const year3Custom = yearlySummaries[2] || { totalRevenue: 0, netProfit: 0 };

  return (
    <div className="mx-auto max-w-7xl px-6 py-6 flex flex-col gap-6 items-stretch">
      {/* Header */}
      <div className="flex flex-col items-start">
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <BarChart3 className="h-8 w-8 text-primary" />
          Combined Platform – 3-Year Pro Forma
        </h1>
        <p className="text-muted-foreground mt-1">
          Subscriptions + Advertising Revenue Financial Model
        </p>
      </div>

      {/* Top-Level Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3 max-w-md">
          <TabsTrigger value="proforma" className="gap-2">
            <FileText className="h-4 w-4" />
            3-Year Pro Forma
          </TabsTrigger>
          <TabsTrigger value="business-model" className="gap-2">
            <TrendingUp className="h-4 w-4" />
            Business Model
          </TabsTrigger>
          <TabsTrigger value="assumptions" className="gap-2">
            <Settings className="h-4 w-4" />
            Assumptions
          </TabsTrigger>
        </TabsList>

        {/* 3-Year Pro Forma Tab */}
        <TabsContent value="proforma" className="mt-6">
          <div className="flex gap-6">
            {/* Left Content */}
            <div className="flex-1 space-y-6">
              {/* Two Column Pro Forma Cards */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* AI-Generated Pro Forma Card */}
                <Card className="border-2 border-primary/20">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <Sparkles className="h-5 w-5 text-primary" />
                        AI-Generated Pro Forma
                      </CardTitle>
                      <Badge variant="secondary" className="text-xs">AI</Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* Scenario Buttons */}
                    <div className="flex gap-2">
                      <Button
                        variant={aiScenario === "conservative" ? "default" : "outline"}
                        size="sm"
                        onClick={() => setAiScenario("conservative")}
                        className="flex-1"
                      >
                        Conservative
                      </Button>
                      <Button
                        variant={aiScenario === "base" ? "default" : "outline"}
                        size="sm"
                        onClick={() => setAiScenario("base")}
                        className="flex-1"
                      >
                        Growth
                      </Button>
                      <Button
                        variant={aiScenario === "aggressive" ? "default" : "outline"}
                        size="sm"
                        onClick={() => setAiScenario("aggressive")}
                        className="flex-1"
                      >
                        Aggressive
                      </Button>
                    </div>

                    {/* 3-Year Summary */}
                    <div className="bg-muted/50 rounded-lg p-4 space-y-3">
                      <h4 className="font-semibold text-sm">3-Year Summary ({aiScenario})</h4>
                      {aiData.map((year) => (
                        <div key={year.year} className="flex justify-between text-sm border-b border-border/50 pb-2 last:border-0 last:pb-0">
                          <span className="text-muted-foreground">Year {year.year}</span>
                          <div className="text-right">
                            <div className="font-medium">{formatCurrency(year.totalRevenue)}</div>
                            <div className="text-xs text-muted-foreground">Net: {formatCurrency(year.netProfit)}</div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Year 3 Highlight */}
                    <div className="bg-primary/5 rounded-lg p-4 border border-primary/20">
                      <div className="text-xs text-muted-foreground mb-1">Year 3 Projected Revenue</div>
                      <div className="text-2xl font-bold text-primary">{formatCurrency(year3AI.totalRevenue)}</div>
                      <div className="text-sm text-muted-foreground">Net Profit: {formatCurrency(year3AI.netProfit)}</div>
                    </div>

                    {/* Download Buttons */}
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" className="flex-1" onClick={() => handleExportPDF("ai")}>
                        <Download className="h-4 w-4 mr-2" />
                        PDF
                      </Button>
                      <Button variant="outline" size="sm" className="flex-1" onClick={() => handleExportExcel("ai")}>
                        <Download className="h-4 w-4 mr-2" />
                        Excel
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                {/* Custom 3-Year Pro Forma Card */}
                <Card className="border-2 border-accent/20">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <Target className="h-5 w-5 text-accent-foreground" />
                        Custom 3-Year Pro Forma
                      </CardTitle>
                      <Button 
                        variant="ghost" 
                        size="sm"
                        onClick={() => setShowShareModal(true)}
                        className="gap-1 h-8"
                      >
                        <Share2 className="h-4 w-4" />
                        Share
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* Custom Assumptions Summary */}
                    <div className="bg-muted/30 rounded-lg p-3 text-sm">
                      <div className="text-muted-foreground mb-2">Based on your custom assumptions:</div>
                      <ul className="space-y-1 text-xs text-muted-foreground">
                        <li>• Subscription + Ad revenue combined</li>
                        <li>• Custom growth rates applied</li>
                        <li>• Creator payouts calculated</li>
                      </ul>
                    </div>

                    {/* 3-Year Summary */}
                    <div className="bg-muted/50 rounded-lg p-4 space-y-3">
                      <h4 className="font-semibold text-sm">3-Year Summary (Custom)</h4>
                      {yearlySummaries.map((year) => (
                        <div key={year.year} className="flex justify-between text-sm border-b border-border/50 pb-2 last:border-0 last:pb-0">
                          <span className="text-muted-foreground">Year {year.year}</span>
                          <div className="text-right">
                            <div className="font-medium">{formatCurrency(year.totalRevenue)}</div>
                            <div className="text-xs text-muted-foreground">Net: {formatCurrency(year.netProfit)}</div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Year 3 Highlight */}
                    <div className="bg-accent/10 rounded-lg p-4 border border-accent/20">
                      <div className="text-xs text-muted-foreground mb-1">Year 3 Projected Revenue</div>
                      <div className="text-2xl font-bold">{formatCurrency(year3Custom.totalRevenue)}</div>
                      <div className="text-sm text-muted-foreground">Net Profit: {formatCurrency(year3Custom.netProfit)}</div>
                    </div>

                    {/* Download Buttons */}
                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" className="flex-1" onClick={() => handleExportPDF("custom")}>
                        <Download className="h-4 w-4 mr-2" />
                        PDF
                      </Button>
                      <Button variant="outline" size="sm" className="flex-1" onClick={() => handleExportExcel("custom")}>
                        <Download className="h-4 w-4 mr-2" />
                        Excel
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => setActiveTab("assumptions")}>
                        <Eye className="h-4 w-4" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Monthly Revenue Chart */}
              <Card>
                <CardHeader>
                  <CardTitle>Monthly Revenue Breakdown</CardTitle>
                  <CardDescription>36-month detailed projection</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-80">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={monthlyProjections}>
                        <CartesianGrid strokeDasharray="3 3" />
                        <XAxis dataKey="periodLabel" />
                        <YAxis />
                        <Tooltip formatter={(value: number) => formatCurrency(value)} />
                        <Legend />
                        <Area 
                          type="monotone" 
                          dataKey="subscriptionRevenue" 
                          stackId="1"
                          stroke="hsl(var(--primary))" 
                          fill="hsl(var(--primary))" 
                          fillOpacity={0.6}
                          name="Subscriptions"
                        />
                        <Area 
                          type="monotone" 
                          dataKey="adRevenue" 
                          stackId="1"
                          stroke="hsl(var(--accent))" 
                          fill="hsl(var(--accent))" 
                          fillOpacity={0.6}
                          name="Ads"
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Right: Sticky Ask Spark Panel */}
            <div className="w-[340px] flex-shrink-0 hidden xl:block">
              <div className="sticky top-20">
                <Card className="flex flex-col h-[calc(100vh-180px)]">
                  <CardHeader className="pb-3 border-b">
                    <CardTitle className="flex items-center gap-2 text-base">
                      <Sparkles className="h-4 w-4 text-primary" />
                      Ask Seeksy Spark
                    </CardTitle>
                    <CardDescription className="text-xs">
                      Financial analysis assistant
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="flex-1 overflow-hidden p-0">
                    <CFOAIChat />
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </TabsContent>

        {/* Business Model Tab */}
        <TabsContent value="business-model" className="mt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <DollarSign className="h-5 w-5" />
                  Revenue Streams
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="p-4 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold mb-2">Subscriptions</h4>
                    <p className="text-sm text-muted-foreground">
                      Creator Pro plans, team subscriptions, and enterprise licensing fees.
                    </p>
                  </div>
                  <div className="p-4 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold mb-2">Advertising Revenue</h4>
                    <p className="text-sm text-muted-foreground">
                      CPM-based podcast ads, pre-roll/mid-roll/post-roll placements, and sponsored content.
                    </p>
                  </div>
                  <div className="p-4 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold mb-2">Platform Fees</h4>
                    <p className="text-sm text-muted-foreground">
                      Transaction fees on creator monetization, booking fees, and premium features.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5" />
                  Growth Drivers
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                    <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
                      <span className="text-sm font-bold text-primary">1</span>
                    </div>
                    <div>
                      <h4 className="font-medium text-sm">Creator Acquisition</h4>
                      <p className="text-xs text-muted-foreground">Monthly creator growth driving ad inventory</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                    <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
                      <span className="text-sm font-bold text-primary">2</span>
                    </div>
                    <div>
                      <h4 className="font-medium text-sm">Advertiser Demand</h4>
                      <p className="text-xs text-muted-foreground">Campaign growth and CPM optimization</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                    <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center flex-shrink-0">
                      <span className="text-sm font-bold text-primary">3</span>
                    </div>
                    <div>
                      <h4 className="font-medium text-sm">Fill Rate Improvement</h4>
                      <p className="text-xs text-muted-foreground">Increasing ad inventory utilization</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Assumptions Tab */}
        <TabsContent value="assumptions" className="mt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Subscription Assumptions</CardTitle>
                <CardDescription>Revenue from creator subscriptions</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-xs">Starting MRR</Label>
                    <div className="text-lg font-semibold">$5,000</div>
                  </div>
                  <div>
                    <Label className="text-xs">Monthly Growth</Label>
                    <div className="text-lg font-semibold">8%</div>
                  </div>
                  <div>
                    <Label className="text-xs">Avg Plan Price</Label>
                    <div className="text-lg font-semibold">$29/mo</div>
                  </div>
                  <div>
                    <Label className="text-xs">Churn Rate</Label>
                    <div className="text-lg font-semibold">5%</div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Advertising Assumptions</CardTitle>
                <CardDescription>Revenue from podcast ads</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-xs">Starting Creators</Label>
                    <div className="text-lg font-semibold">50</div>
                  </div>
                  <div>
                    <Label className="text-xs">Creator Growth</Label>
                    <div className="text-lg font-semibold">10%/mo</div>
                  </div>
                  <div>
                    <Label className="text-xs">Blended CPM</Label>
                    <div className="text-lg font-semibold">$25</div>
                  </div>
                  <div>
                    <Label className="text-xs">Fill Rate</Label>
                    <div className="text-lg font-semibold">60%</div>
                  </div>
                  <div>
                    <Label className="text-xs">Creator Rev Share</Label>
                    <div className="text-lg font-semibold">70%</div>
                  </div>
                  <div>
                    <Label className="text-xs">Listens/Episode</Label>
                    <div className="text-lg font-semibold">500</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>

      {/* Share Modal */}
      <Dialog open={showShareModal} onOpenChange={setShowShareModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Share Pro Forma with Board</DialogTitle>
            <DialogDescription>
              Share this custom pro forma with board members and investors.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <p className="text-sm text-muted-foreground">
              This will make the current custom pro forma available in the Board Portal.
              Board members will be able to view and download the report.
            </p>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowShareModal(false)}>
              Cancel
            </Button>
            <Button onClick={handleShareWithBoard} disabled={isSharing}>
              {isSharing ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Sharing...
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-4 w-4 mr-2" />
                  Share with Board
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
